# Generated by Django 5.2.16 on 2026-07-29 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmake',
            old_name='descritption',
            new_name='description',
        ),
    ]
